-- Create grid_references table
CREATE TABLE grid_references (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  canvas_width INTEGER NOT NULL,
  canvas_height INTEGER NOT NULL,
  reference_image_url TEXT NOT NULL,
  grid_config JSONB NOT NULL,
  analysis JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE grid_references ENABLE ROW LEVEL SECURITY;

-- Allow public read access to grid_references
CREATE POLICY "Public profiles are viewable by everyone."
  ON grid_references FOR SELECT
  USING ( true );

-- Insert seed data into grid_references
INSERT INTO grid_references (name, category, canvas_width, canvas_height, reference_image_url, grid_config, analysis) VALUES
  ('Swiss Style Exhibition', 'Poster', 800, 1200, 'https://images.unsplash.com/photo-1544002621-e73bc5b4c10a?q=80&w=800&h=1200&fit=crop', '{"type": "column", "columns": 4, "gutter": 20, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Typographic Movie Poster', 'Poster', 800, 1200, 'https://images.unsplash.com/photo-1510251141369-122e2fec19a1?q=80&w=800&h=1200&fit=crop', '{"type": "column", "columns": 6, "gutter": 16, "margin": 30, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "6 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Minimalist Event Poster', 'Poster', 800, 1200, 'https://images.unsplash.com/photo-1518331526-728b7e2cc45b?q=80&w=800&h=1200&fit=crop', '{"type": "modular", "columns": 3, "rows": 4, "gutter": 20, "margin": 50, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "3x4 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Fashion Magazine Spread', 'Editorial', 1200, 800, 'https://images.unsplash.com/photo-1584446599763-71d533ab6233?q=80&w=1200&h=800&fit=crop', '{"type": "column", "columns": 12, "gutter": 16, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "12 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Architecture Journal', 'Editorial', 1200, 800, 'https://images.unsplash.com/photo-1582216656752-0941328b9c10?q=80&w=1200&h=800&fit=crop', '{"type": "modular", "columns": 8, "rows": 6, "gutter": 20, "margin": 60, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "8x6 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Lifestyle Article', 'Editorial', 1200, 800, 'https://images.unsplash.com/photo-1512411961623-c5dc56453673?q=80&w=1200&h=800&fit=crop', '{"type": "column", "columns": 6, "gutter": 24, "margin": 48, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "6 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Instagram Carousel Square', 'Social Media', 1080, 1080, 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1080&h=1080&fit=crop', '{"type": "modular", "columns": 6, "rows": 6, "gutter": 12, "margin": 30, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "6x6 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Product Drop Promo', 'Social Media', 1080, 1080, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1080&h=1080&fit=crop', '{"type": "modular", "columns": 4, "rows": 4, "gutter": 20, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4x4 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Quote Post', 'Social Media', 1080, 1080, 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=1080&h=1080&fit=crop', '{"type": "column", "columns": 4, "gutter": 20, "margin": 80, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('SaaS Landing Page', 'Web/UI', 1440, 900, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1440&h=900&fit=crop', '{"type": "column", "columns": 12, "gutter": 24, "margin": 120, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "12 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('E-commerce Product Page', 'Web/UI', 1440, 900, 'https://images.unsplash.com/photo-1481437156560-3205f6a55735?q=80&w=1440&h=900&fit=crop', '{"type": "column", "columns": 12, "gutter": 30, "margin": 80, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "12 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Dashboard Interface', 'Web/UI', 1440, 900, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1440&h=900&fit=crop', '{"type": "modular", "columns": 12, "rows": 8, "gutter": 16, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "12x8 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Stationery Mockup', 'Branding', 1200, 900, 'https://images.unsplash.com/photo-1598114674722-e3a105f93ea8?q=80&w=1200&h=900&fit=crop', '{"type": "column", "columns": 6, "gutter": 20, "margin": 50, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "6 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Logo Presentation', 'Branding', 1200, 900, 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1200&h=900&fit=crop', '{"type": "modular", "columns": 4, "rows": 3, "gutter": 30, "margin": 60, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4x3 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Brand Guidelines Page', 'Branding', 1200, 900, 'https://images.unsplash.com/photo-1507238692062-5a042e9e80b5?q=80&w=1200&h=900&fit=crop', '{"type": "column", "columns": 8, "gutter": 24, "margin": 80, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "8 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Billboard Campaign', 'Advertising/Marketing', 1600, 800, 'https://images.unsplash.com/photo-1542204637-e67bc7d41e48?q=80&w=1600&h=800&fit=crop', '{"type": "column", "columns": 8, "gutter": 40, "margin": 100, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "8 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Banner Ad', 'Advertising/Marketing', 1200, 600, 'https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1200&h=600&fit=crop', '{"type": "column", "columns": 6, "gutter": 20, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "6 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Corporate Flyer', 'Flyer', 850, 1100, 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=850&h=1100&fit=crop', '{"type": "column", "columns": 4, "gutter": 16, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Club Night Flyer', 'Flyer', 850, 1100, 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=850&h=1100&fit=crop', '{"type": "modular", "columns": 4, "rows": 5, "gutter": 12, "margin": 30, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4x5 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Minimalist Business Card', 'Business Card', 1050, 600, 'https://images.unsplash.com/photo-1589304026857-e923e200c622?q=80&w=1050&h=600&fit=crop', '{"type": "column", "columns": 3, "gutter": 10, "margin": 30, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "3 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Creative Studio Card', 'Business Card', 1050, 600, 'https://images.unsplash.com/photo-1559055816-4dc4a86b97b0?q=80&w=1050&h=600&fit=crop', '{"type": "modular", "columns": 4, "rows": 2, "gutter": 10, "margin": 40, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "4x2 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Keynote Title Slide', 'Presentation', 1920, 1080, 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1920&h=1080&fit=crop', '{"type": "column", "columns": 12, "gutter": 30, "margin": 100, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "12 Column Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}'),
  ('Data Slide', 'Presentation', 1920, 1080, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1920&h=1080&fit=crop', '{"type": "modular", "columns": 12, "rows": 6, "gutter": 20, "margin": 80, "color": "#f43f5e", "opacity": 0.5, "isVisible": true}', '{"gridNotes": "12x6 Modular Grid", "structure": "Professional Layout Reference", "alignment": "Grid Aligned", "style": "Professional Design", "mainAlignment": "Strict adherence"}');

-- Create storage bucket for grid references
INSERT INTO storage.buckets (id, name, public) VALUES ('grid-references', 'grid-references', true) ON CONFLICT DO NOTHING;

CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'grid-references');
