import { ReferenceLayout } from "./types";

export const categories = [
  "Social Media",
  "Poster",
  "Flyer",
  "Presentation",
  "Business Card",
  "Editorial",
];

export const predefinedLayouts: ReferenceLayout[] = [
  {
    id: "editorial-magazine-12col",
    name: "Classic Editorial Spread",
    category: "Editorial",
    canvasWidth: 1200,
    canvasHeight: 800,
    gridConfig: {
      type: "column",
      columns: 12,
      gutter: 20,
      margin: 60,
      color: "#f43f5e",
      opacity: 0.3,
      isVisible: true,
    },
    analysis: {
      gridNotes: "12 Columns",
      structure: "Headline → Image → Supporting Copy",
      alignment: "Left aligned",
      style: "Asymmetrical",
      mainAlignment: "Column 2 → Column 10",
    },
    elements: [
      {
        id: "bg",
        type: "background",
        position: { x: 0, y: 0, width: 1200, height: 800 },
        shapeStyle: { backgroundColor: "#f9fafb" },
        isHidden: false,
        isLocked: true,
      },
      {
        id: "img-main",
        type: "image",
        label: "Main Image",
        position: { x: 60, y: 60, width: 490, height: 680 },
        imageStyle: { objectFit: "cover", opacity: 1 },
        shapeStyle: { backgroundColor: "#e5e7eb" },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "headline",
        type: "text",
        label: "Headline",
        content: "THE FUTURE\nOF DESIGN.",
        position: { x: 590, y: 60, width: 550, height: 200 },
        textStyle: {
          fontSize: 72,
          fontWeight: "800",
          textAlign: "left",
          color: "#111827",
          lineHeight: 1.1,
          textTransform: "uppercase",
          letterSpacing: -2,
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "subhead",
        type: "text",
        label: "Subheading",
        content: "How structural grid systems dictate the rhythm of modern reading experiences across print and digital screens.",
        position: { x: 590, y: 280, width: 400, height: 100 },
        textStyle: {
          fontSize: 20,
          fontWeight: "500",
          textAlign: "left",
          color: "#4b5563",
          lineHeight: 1.5,
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "body-1",
        type: "text",
        label: "Body Copy",
        content: "Grids do not restrict creativity; they provide a foundation upon which creativity can safely scale. When establishing an editorial layout, leveraging a 12-column grid provides maximum flexibility. You can span content across 2, 3, 4, or 6 columns instantly creating dynamic tension.\n\nNotice how the headline spans a distinct number of columns compared to the body text. This asymmetric balance anchors the eye.",
        position: { x: 590, y: 400, width: 250, height: 340 },
        textStyle: {
          fontSize: 14,
          fontWeight: "400",
          textAlign: "left",
          color: "#374151",
          lineHeight: 1.6,
        },
        isHidden: false,
        isLocked: false,
      }
    ]
  },
  {
    id: "social-promo-modular",
    name: "Product Drop Promo",
    category: "Social Media",
    canvasWidth: 1080,
    canvasHeight: 1080,
    gridConfig: {
      type: "modular",
      columns: 6,
      rows: 6,
      gutter: 16,
      margin: 40,
      color: "#3b82f6",
      opacity: 0.3,
      isVisible: true,
    },
    analysis: {
      gridNotes: "6×6 Modular",
      structure: "Top Label → Central Subject → Floating Badges → Bottom CTA",
      alignment: "Center aligned focus with edge-aligned accents",
      style: "Symmetrical Core / Asymmetrical Accents",
      mainAlignment: "Modules 2-5",
    },
    elements: [
      {
        id: "bg",
        type: "background",
        position: { x: 0, y: 0, width: 1080, height: 1080 },
        shapeStyle: { backgroundColor: "#0f172a" },
        isHidden: false,
        isLocked: true,
      },
      {
        id: "img-main",
        type: "image",
        label: "Product Image",
        position: { x: 196, y: 196, width: 688, height: 688 },
        imageStyle: { objectFit: "contain", opacity: 1 },
        shapeStyle: { backgroundColor: "transparent" },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "label",
        type: "text",
        label: "Top Label",
        content: "NEW ARRIVAL",
        position: { x: 40, y: 60, width: 1000, height: 50 },
        textStyle: {
          fontSize: 24,
          fontWeight: "700",
          textAlign: "center",
          color: "#60a5fa",
          lineHeight: 1,
          letterSpacing: 4,
          textTransform: "uppercase"
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "headline",
        type: "text",
        label: "Headline",
        content: "AURA HEADPHONES",
        position: { x: 40, y: 120, width: 1000, height: 100 },
        textStyle: {
          fontSize: 84,
          fontWeight: "900",
          textAlign: "center",
          color: "#ffffff",
          lineHeight: 1,
          textTransform: "uppercase",
          letterSpacing: -1,
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "price-badge",
        type: "shape",
        label: "Price Badge",
        position: { x: 800, y: 250, width: 180, height: 180 },
        shapeStyle: { backgroundColor: "#3b82f6", borderRadius: 90 },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "price-text",
        type: "text",
        label: "Price Text",
        content: "$299",
        position: { x: 800, y: 310, width: 180, height: 60 },
        textStyle: {
          fontSize: 42,
          fontWeight: "800",
          textAlign: "center",
          color: "#ffffff",
          lineHeight: 1,
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "cta",
        type: "shape",
        label: "CTA Button",
        position: { x: 340, y: 920, width: 400, height: 80 },
        shapeStyle: { backgroundColor: "#ffffff", borderRadius: 40 },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "cta-text",
        type: "text",
        label: "CTA Text",
        content: "SHOP NOW",
        position: { x: 340, y: 940, width: 400, height: 40 },
        textStyle: {
          fontSize: 24,
          fontWeight: "800",
          textAlign: "center",
          color: "#0f172a",
          lineHeight: 1,
          letterSpacing: 2,
        },
        isHidden: false,
        isLocked: false,
      }
    ]
  },
  {
    id: "poster-swiss-4col",
    name: "Swiss Style Poster",
    category: "Poster",
    canvasWidth: 800,
    canvasHeight: 1200,
    gridConfig: {
      type: "column",
      columns: 4,
      gutter: 24,
      margin: 48,
      color: "#f59e0b",
      opacity: 0.3,
      isVisible: true,
    },
    analysis: {
      gridNotes: "4 Columns Strict",
      structure: "Top Left Meta → Massive Headline → Bottom Right Anchors",
      alignment: "Strict Left aligned to columns",
      style: "Minimalist / Swiss Typography",
      mainAlignment: "Column 1 and Column 3 constraints",
    },
    elements: [
      {
        id: "bg",
        type: "background",
        position: { x: 0, y: 0, width: 800, height: 1200 },
        shapeStyle: { backgroundColor: "#fafafa" },
        isHidden: false,
        isLocked: true,
      },
      {
        id: "meta-1",
        type: "text",
        label: "Exhibition Text",
        content: "Exhibition 2026\nMuseum of Modern Art\nZürich",
        position: { x: 48, y: 48, width: 200, height: 100 },
        textStyle: {
          fontSize: 16,
          fontWeight: "600",
          textAlign: "left",
          color: "#ef4444",
          lineHeight: 1.4,
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "headline",
        type: "text",
        label: "Headline",
        content: "STRUCTURAL\nHARMONY.",
        position: { x: 48, y: 350, width: 700, height: 400 },
        textStyle: {
          fontSize: 130,
          fontWeight: "900",
          textAlign: "left",
          color: "#171717",
          lineHeight: 0.9,
          letterSpacing: -4,
          textTransform: "uppercase"
        },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "shape-accent",
        type: "shape",
        label: "Accent Shape",
        position: { x: 412, y: 48, width: 340, height: 160 },
        shapeStyle: { backgroundColor: "#ef4444" },
        isHidden: false,
        isLocked: false,
      },
      {
        id: "footer-text",
        type: "text",
        label: "Date details",
        content: "24 OCT — 12 NOV\nFREE ADMISSION",
        position: { x: 412, y: 1050, width: 340, height: 100 },
        textStyle: {
          fontSize: 24,
          fontWeight: "700",
          textAlign: "left",
          color: "#171717",
          lineHeight: 1.2,
        },
        isHidden: false,
        isLocked: false,
      }
    ]
  }
];
